# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='log_data.proto',
  package='power_data',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0elog_data.proto\x12\npower_data\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaf\x02\n\x08PowerLog\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12 \n\x18Switching_Power_Input_mA\x18\x02 \x01(\x05\x12 \n\x18Switching_Power_Input_mV\x18\x03 \x01(\x05\x12\x18\n\x10\x42\x61ttery_Input_mA\x18\x04 \x01(\x05\x12\x18\n\x10\x42\x61ttery_Input_mV\x18\x05 \x01(\x05\x12\x1b\n\x13SBC_Power_Supply_mA\x18\x06 \x01(\x05\x12\x1b\n\x13SBC_Power_Supply_mV\x18\x07 \x01(\x05\x12 \n\x18\x41\x63tuator_Power_Supply_mA\x18\x08 \x01(\x05\x12 \n\x18\x41\x63tuator_Power_Supply_mV\x18\t \x01(\x05\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_POWERLOG = _descriptor.Descriptor(
  name='PowerLog',
  full_name='power_data.PowerLog',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='power_data.PowerLog.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Switching_Power_Input_mA', full_name='power_data.PowerLog.Switching_Power_Input_mA', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Switching_Power_Input_mV', full_name='power_data.PowerLog.Switching_Power_Input_mV', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Battery_Input_mA', full_name='power_data.PowerLog.Battery_Input_mA', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Battery_Input_mV', full_name='power_data.PowerLog.Battery_Input_mV', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SBC_Power_Supply_mA', full_name='power_data.PowerLog.SBC_Power_Supply_mA', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='SBC_Power_Supply_mV', full_name='power_data.PowerLog.SBC_Power_Supply_mV', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Actuator_Power_Supply_mA', full_name='power_data.PowerLog.Actuator_Power_Supply_mA', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Actuator_Power_Supply_mV', full_name='power_data.PowerLog.Actuator_Power_Supply_mV', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=367,
)

_POWERLOG.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['PowerLog'] = _POWERLOG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PowerLog = _reflection.GeneratedProtocolMessageType('PowerLog', (_message.Message,), {
  'DESCRIPTOR' : _POWERLOG,
  '__module__' : 'log_data_pb2'
  # @@protoc_insertion_point(class_scope:power_data.PowerLog)
  })
_sym_db.RegisterMessage(PowerLog)


# @@protoc_insertion_point(module_scope)
